- name: Install necessary python modules
  apt:
    name: python3-pymysql
    state: present
  become: true

- name: Install MariaDB server
  apt:
    name: mariadb-server
    state: present
  notify: restart mariadb
  become: true

- name: Ensure MariaDB service is running
  service:
    name: mariadb
    state: started
    enabled: yes
  become: true

# - name: Set MariaDB root password
#   mysql_user:
#     name: root
#     password: "{{ mariadb_root_password }}"
#     login_unix_socket: /var/run/mysqld/mysqld.sock
#     state: present
#   become: true

- name: Ensure databases exist
  mysql_db:
    name: "{{ k3s_database }}"
    # login_user: root
    # login_password: "{{ mariadb_root_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    state: present
  become: true

- name: Ensure users exist
  mysql_user:
    # login_user: root
    # login_password: "{{ mariadb_root_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: "{{ k3s_database_user }}"
    password: "{{ k3s_database_pass }}"
    host: "{{ k3s_client_host }}"
    priv: "{{ k3s_database }}.*:ALL"
    state: present
  become: true

- name: Configurar bind-address en MariaDB
  ansible.builtin.lineinfile:
    path: /etc/mysql/mariadb.conf.d/50-server.cnf
    regexp: '^bind-address\s*='
    line: 'bind-address = 0.0.0.0'
  become: true
  notify: restart mariadb