- name: Download k3s install script
  get_url:
    url: "{{ k3s_install_script }}"
    dest: "/tmp/install-k3s.sh"
    mode: '0755'

- name: Install k3s worker
  command: "/tmp/install-k3s.sh agent --server https://{{ first_master_ip }}:6443 --token {{ k3s_cluster_secret }} --with-node-id"
  become: true
