- name: Formateamos volumen ebs para prometheus
  become: true
  filesystem:
    fstype: ext4
    dev: /dev/sdf

- name: Crear directorio de montaje
  file:
    path: /mnt/prometheus
    state: directory

- name: Montamos el volumen
  mount:
    path: /mnt/prometheus
    src: /dev/sdf
    fstype: ext4
    state: mounted

- name: Instala controladores necesarios para longhorn
  apt:
    name: "{{item}}"
    state: present
    update_cache: true
    allow_downgrade: true
  loop:
    - open-iscsi
    - nfs-common
    # - bash
    # - curl
    # - findmnt
    # - grep
    # - awk
    # - blkid
    # - lsblk
  become: true

# - name: Download k3s install script
#   get_url:
#     url: "{{ k3s_install_script }}"
#     dest: "/tmp/install-k3s.sh"
#     mode: '0755'

# - name: Install k3s worker
  # command: "/tmp/install-k3s.sh agent --server https://{{ first_master_dns }}:6443 --token {{ k3s_cluster_secret }} --with-node-id"
  # become: true

- name: install k3s master
  shell: |
    curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION="{{ install_k3s_version }}" sh -s - agent \
    --server https://{{ first_master_dns }}:6443 \
    --token {{ k3s_cluster_secret }} \
    --with-node-id
  args:
    executable: /bin/bash